linkernetworks/vortex

- Jenkinsfile
- jenkins/Dockerfile
- jenkins/entry.sh
- jenkins/home/jenkins/.bash_logout
- jenkins/home/jenkins/.bashrc
- jenkins/home/jenkins/.profile
- Jenkinsfile: entry point for jenkins
- jenkins/: docker image for jenkins agent
> Support Jenkins

- src/net/http/handler_test.go
- src/net/http/response_test.go
- src/net/http/responsetest/assert_test.go
- net/response/*
- net/handler.go
- net/response.go
> Add more testing for src/net package

- src/entity/storage_provider.go
- src/server/handler_storage_provider.go
- src/server/handler_storage_provider_test.go
- src/server/route.go
- vendor/vendor.json
The storage-provider is used to setup the storage for system and it should setup all resources we need for kubernetes (storageClass, storage-provisioner).
- In this patch, we only handle the mongo document.
- We only support the NFS now and it's easy to add other storage in the field.
- For NFS, we will setup the deployment and storageClass for nfs-client provisioner.
- For GlusterFS,  we only setup the storageClass for glusterFS provisioner
> The restful handler of storageprovider

- src/kubernetes/kubectl.go
- src/kubernetes/nodes.go
- src/net/http/handler.go
- src/net/http/query/query.go
- src/net/http/response.go
- src/net/http/response_test.go
- src/server/handler_version.go
- src/server/route.go
- src/web/context.go
Fix following issues
GoFmt
Go_Vet
- Unused example (Wrong function name and usage)
GoLint
- Commend function or change to private function (not-exposed)
> Fix the goreports.

- src/entity/network.go
- src/server/handler_network.go
- src/server/handler_network_test.go
- src/server/handler_storage_provider.go
- src/server/route.go
We replace the "BridgeName" and "DisplayName" by "Name" now.
Use can create duplicated name on different node but can't in the same node.
> Refactor the field of network entity.

- .travis.yml
- src/config/config.go
- src/server/handler_network_test.go
- src/serviceprovider/serviceprovider.go
- For travis
- Install OpenvSwitch
- Run a gRPC server
- Use the sudo to run the testing (we need to create a veth for testing)
- For testing
- Use the suite to wrapper the common variable for all testing.
> [WIP]Fix the testing for gRPC client

- .travis.yml
- Jenkinsfile
- src/server/handler_prometheus_test.go
- Use the environment TEST_PROMETHEUS to check do we need to test the function of prometheus
> Add the testing condition for prometheus

- src/server/handler_network.go
- src/server/handler_network_test.go
- src/server/handler_storage_provider.go
- src/server/handler_volume.go
- src/server/handler_volume_test.go
- src/server/route.go
- Also rename the `as` to `sp`
- Add the testing (valid/invalid).
> Implement the function to list the documents of volumes 

- src/entity/network.go
- src/networkprovider/fake_test.go
- src/networkprovider/network.go
- src/networkprovider/network_test.go
- src/networkprovider/ovs.go
- src/networkprovider/ovs_test.go
- src/server/handler_network_test.go
For the network, we should support the cluster/single network.
For cluster network, it should create network for all nodes. Otherwise use the nodename from the parameter.
> Support two types of network.

- jenkins/entry.sh
There're some random fail when testing the prometheus in the jenkins.
I guess the prometheus docker doesn't running while go testing, so we use the sleep to test the prometheus.
> Wait the prometheus

- src/entity/storage.go
- src/kubernetes/deployment.go
- src/kubernetes/deployment_test.go
- src/server/handler_storage.go
- src/server/handler_storage_test.go
- src/storageprovider/fake.go
- src/storageprovider/fake_test.go
- src/storageprovider/nfs.go
- src/storageprovider/nfs_test.go
- src/storageprovider/storage.go
- src/storageprovider/storage_test.go
If the type is `nfs`, we will create a deployment like this.
```
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
name: nfs-client-provisioner
spec:
replicas: 1
strategy:
type: Recreate
template:
metadata:
labels:
app: nfs-client-provisioner
spec:
serviceAccount: nfs-provisioner
containers:
- name: nfs-client-provisioner
image: quay.io/kubernetes_incubator/nfs-provisioner:latest
imagePullPolicy: IfNotPresent
volumeMounts:
- name: nfs-client-root
mountPath: /persistentvolumes
env:
- name: PROVISIONER_NAME
value: vortex.io/nfs
- name: NFS_SERVER
value: 192.168.6.135
- name: NFS_PATH
value: /exports
volumes:
- name: nfs-client-root
nfs:
server: 192.168.6.135
path: /exports
```
> Create a deployment for storage.

- src/kubernetes/pods.go
- src/kubernetes/pods_test.go
- src/kubernetes/pvc.go
- src/kubernetes/pvc_test.go
Use the namespace in the kuberctl object, we don't need to pass the namespace into each function.
> Use the namespace in the kubectl object

- deploy/kubernetes/auth/clusterrole.yaml
- deploy/kubernetes/auth/clusterrolebinding.yaml
- deploy/kubernetes/auth/nfs-provisioner.yaml
- src/entity/storage.go
- src/kubernetes/storageclass.go
- src/kubernetes/storageclass_test.go
- src/server/handler_storage_test.go
- src/storageprovider/nfs.go
- src/storageprovider/nfs_test.go
Implement the  NFS-Provisioner function, we will create the deployment and storageClass now.
> Create/Delete the storageClass when we create/delete the storage

- src/entity/volume.go
- src/server/handler_volume.go
- src/server/handler_volume_test.go
- src/storageprovider/nfs_test.go
- src/volume/volume.go
- src/volume/volume_test.go
- Create the Volume(PVC) based on the storage(StorageClass) we created before.
> Support the create/delete for volume(pvc) via restful API

- src/storageprovider/nfs.go
- src/storageprovider/nfs_test.go
We can't delete the storage if the storage is used by some volume
> Check the volume before deleting the storage

- src/server/handler_prometheus.go
Prometheus's API cannot give us the accurate error, so we only can know what problem we encounter by the error message.
> BUGFIX: Change the response status form BadRequest to InternalServerError

- API.md
- src/entity/storage.go
- src/entity/storage_nfs.go
- src/entity/volume.go
- src/server/handler_volume.go
- src/server/handler_volume_test.go
- src/storageprovider/nfs.go
- src/storageprovider/nfs_test.go
- src/storageprovider/storage.go
- src/storageprovider/storage_test.go
- src/volume/volume.go
- src/volume/volume_test.go
1. 將 NFS 的結構攤平到 Storage 那邊，前端那邊比較喜歡這樣處理 (我們就保證只提供 NFS 的功能，不然攤平後很難擴展參數)
2. 將 Volume 設定 Metaname的部分改寫，不用存入 DB, Volume物件自己提供function去計算
> Flat the storage entity and change the meta name of volume.

- src/entity/network.go
- src/networkprovider/fake.go
- src/networkprovider/fake_test.go
- src/networkprovider/network.go
- src/networkprovider/ovs_netdev.go
- src/networkprovider/ovs_system.go
- src/server/handler_network_test.go
Embed the entity.network to each network. we have already flatted all parameter for all network types.
> Remove the parameter for fake network

- src/entity/metrics_node.go
- src/prometheuscontroller/expression.go
If the NIC does't have a pic id, then the value will be an empty string
> DEV: Add pci id column

- src/entity/pod.go
- src/pod/pod.go
- src/pod/pod_test.go
- src/server/handler_pod_test.go
- src/utils/intersection.go
- src/utils/intersection_test.go
- src/utils/net.go
- src/utils/net_test.go
1. 支援 Network 參數，可將該 Pod 與先前創立的 Network 綁定
2. 參考該 Yaml 
https://github.com/linkernetworks/network-controller/blob/master/deploy/client/clientpodtest.yaml
> Support the multiple network when creating Pod

- src/entity/pod.go
- src/pod/pod.go
Related issue: #154 
close #154 
- Update PodNetwork Entity: Add PodRoute structure & add a routes attribute.
- Fix typo of comment
- Update "generateClientCommand"  to support add route command. In this time, I just use array[0], because it's limited with Network-controller client the main function.
> Add route entity & update generateClientCommand

- src/server/handler_authenticate.go
- src/server/jwt.go
- src/server/jwt_test.go
- src/server/route.go
- src/server/route_filter.go
- vendor/vendor.json
Token-Based Auth 使用者登入驗證POC 使用JWT 驗證 API 登入驗證機制，這個PR想討論實作可行性
> JWT POC for API
